POST http://localhost:2525/imposters/4545/stubs
Content-Type: application/json

{
  "stub": {
    "predicates": [
      { "equals": { "method": "GET" } }
    ],
    "responses": [
      {
        "is": {
          "statusCode": 404,
          "headers": { "Content-Type": "application/json" },
          "body": { 
            "error": "not_found", 
            "message": "O recurso solicitado não existe neste servidor virtual." 
          }
        }
      }
    ]
  }
}

### Teste Exercício 15 (Deve dar 404 Not Found)
GET http://localhost:4545/api/rota/que/nao/existe